// Generated by CoffeeScript 1.6.3
define(['mediator', 'pricePanel', 'orderPanel'], function(Mediator, PricePanel, OrderPanel) {
  return (function() {
    document.getElementById("priceInput").addEventListener("change", function() {
      if (!!this.value) {
        return Mediator.broadcast("BidClick", [this.value]);
      }
    });
    Mediator.registerComponent("pricePanel", new PricePanel());
    Mediator.registerComponent("orderPanel", new OrderPanel());
  })();
});
