// Generated by CoffeeScript 1.6.3
require.config({
    paths: {
        'mediator': 'Mediator',
        'pricePanel': 'PricePanel',
        'orderPanel': 'OrderPanel',
        'main': 'main'
    }
});

if (!window.requireTestMode) {
    require(['main'], function () {
    });
}

/*
 //@ sourceMappingURL=config.map
 */
