// Generated by CoffeeScript 1.6.3
define(["newContentLoader"], function(contentLoader) {
  var genericModule;
  genericModule = function(moduleId) {
    return {
      render: function(button, containerId, dataUrl) {
        contentLoader.getNewContent(button, containerId, dataUrl);
        return console.log("Module " + moduleId + " is rendered...");
      }
    };
  };
  return genericModule;
});

/*
//@ sourceMappingURL=generic-module.map
*/
