// Generated by CoffeeScript 1.6.3
var Auction;

define(function(require, exports, module) {
  return module.exports = Auction;
});

Auction = (function() {
  function Auction(auctionState, item, bestBid, auctionId) {
    this.auctionState = auctionState;
    this.item = item;
    this.bestBid = bestBid;
    this.auctionId = auctionId;
  }

  Auction.prototype.toJson = function() {
    return JSON.stringify(this);
  };

  return Auction;

})();

console.log("auctionDto module loaded");

/*
//@ sourceMappingURL=Auction.map
*/
