// Generated by CoffeeScript 1.6.3
var AuctionMessage;

define(function(require, exports, module) {
  return module.exports = AuctionMessage;
});

AuctionMessage = (function() {
  function AuctionMessage(type, data, auctionId) {
    this.type = type;
    this.data = data;
    this.auctionId = auctionId;
  }

  AuctionMessage.prototype.toJson = function() {
    return JSON.stringify(this);
  };

  return AuctionMessage;

})();

console.log("auctionMessageDto module loaded");

/*
//@ sourceMappingURL=AuctionMessage.map
*/
