// Generated by CoffeeScript 1.6.3
define(["newContentLoader", "auctionApp"], function(contentLoader, AuctionApp) {
  var wayToGive;
  console.log("way-to-give module is loaded");
  wayToGive = function() {
    return {
      rendered: false,
      startAuction: function() {
        var auctionApp, myBid, myCombo, myLogin;
        auctionApp = new AuctionApp();
        myCombo = document.getElementById("comboID");
        myLogin = document.getElementById("loginID");
        myCombo.addEventListener("change", (function(event) {
          auctionApp.updateControls();
          return false;
        }), false);
        document.getElementById("gotoAuction-button").onclick = function() {
          auctionApp.gotoAuction(myLogin.value, myCombo.options[myCombo.selectedIndex].value);
          return false;
        };
        myBid = document.getElementById("bidInput");
        document.getElementById("bid_button").onclick = function(e) {
          auctionApp.placeBid(myBid.value, myCombo.options[myCombo.selectedIndex].value);
          return false;
        };
        auctionApp.launch();
        return console.log("auctionApp module is launched");
      },
      render: function() {
        var dataUrl, newContainerID, whatWeDoButton;
        whatWeDoButton = "way-to-give";
        newContainerID = "way-to-give-container";
        dataUrl = "assets/html-includes/way-to-give.html";
        contentLoader.getNewContent(whatWeDoButton, newContainerID, dataUrl);
        this.rendered = true;
        console.log("way-to-give module is rendered");
      },
      init: function() {
        return console.log("way-to-give init");
      }
    };
  };
  return wayToGive;
});

/*
//@ sourceMappingURL=way-to-give.map
*/
