// Generated by CoffeeScript 1.6.2
define(['order!login', 'order!donation', 'order!campaigns-map', 'order!svg-pie-chart', 'modules/generic-module'], function() {
  return (function() {
    var initModule, lazyLoadingEventHandlerFactory, module, modulesConfig, way_to_give, what_we_do, where_we_work, who_we_are, _i, _len;

    way_to_give = document.getElementById("way-to-give");
    what_we_do = document.getElementById("what-we-do");
    who_we_are = document.getElementById("who-we-are");
    where_we_work = document.getElementById("where-we-work");
    modulesConfig = [
      {
        moduleId: "wayToGive",
        button: way_to_give,
        containerId: "way-to-give-container",
        htmlContentUrl: "assets/html-includes/way-to-give.html"
      }, {
        moduleId: "whatWeDo",
        button: what_we_do,
        containerId: "what-we-do-container",
        htmlContentUrl: "assets/html-includes/what-we-do.html"
      }, {
        moduleId: "whoWeAre",
        button: who_we_are,
        container: "who-we-are-container",
        htmlContentUrl: "assets/html-includes/who-we-are.html"
      }, {
        moduleId: "whereWeWork",
        button: where_we_work,
        container: "where-we-work-container",
        htmlContentUrl: "assets/html-includes/who-we-are.html"
      }
    ];
    lazyLoadingEventHandlerFactory = function(moduleId, button, containerId, htmlContentPath) {
      var clickEventHandler;

      return clickEventHandler = function(event) {
        var module;

        if (module === "loading") {
          return;
        }
        if (typeof module !== "undefined" && module !== null) {
          return module.render(button.id, containerId, htmlContentPath);
        } else {
          module = "loading";
          return require(["modules/generic-module"], function(genericModule) {
            module = new genericModule(moduleId);
            return module.render(button.id, containerId, htmlContentPath);
          });
        }
      };
    };
    initModule = function(module) {
      var handler;

      handler = lazyLoadingEventHandlerFactory(module.moduleId, module.button, module.container, module.htmlContentUrl);
      return module.button.addEventListener("click", handler, false);
    };
    for (_i = 0, _len = modulesConfig.length; _i < _len; _i++) {
      module = modulesConfig[_i];
      initModule(module);
    }
    console.log("app is loaded");
  })();
});

/*
//@ sourceMappingURL=main.map
*/
