// Generated by CoffeeScript 1.6.2
define(['order!login', 'order!donation', 'order!svg-pie-chart'], function() {
  console.log("app is loaded");
  return (function() {
    var lazyLoadingEventHandlerFactory, wayToGiveHandleClick, way_to_give, whatWeDoHandleClick, what_we_do, whereWeWorkHandleClick, where_we_work, whoWeAreHandleClick, who_we_are;

    way_to_give = document.getElementById("way-to-give");
    what_we_do = document.getElementById("what-we-do");
    who_we_are = document.getElementById("who-we-are");
    where_we_work = document.getElementById("where-we-work");
    lazyLoadingEventHandlerFactory = function(moduleId, button, containerId, htmlContentPath) {
      var clickEventHandler;

      return clickEventHandler = function(event) {
        var module;

        if (module === "loading") {
          return;
        }
        if (typeof module !== "undefined" && module !== null) {
          return module.render();
        } else {
          module = "loading";
          return require(["modules/generic-module"], function(genericModule) {
            module = new genericModule(moduleId);
            return module.render(button, containerId, htmlContentPath);
          });
        }
      };
    };
    wayToGiveHandleClick = lazyLoadingEventHandlerFactory("wayToGive", way_to_give, "way-to-give-container", "assets/html-includes/way-to-give.html");
    whatWeDoHandleClick = lazyLoadingEventHandlerFactory("whatWeDo", what_we_do, "what-we-do-container", "assets/html-includes/what-we-do.html");
    whoWeAreHandleClick = lazyLoadingEventHandlerFactory("whatWeAre", who_we_are, "who-we-are-container", "assets/html-includes/who-we-are.html");
    whereWeWorkHandleClick = lazyLoadingEventHandlerFactory("whereWeWork", where_we_work, "where-we-work-container", "assets/html-includes/where-we-work.html");
    way_to_give.addEventListener("click", wayToGiveHandleClick, false);
    what_we_do.addEventListener("click", whatWeDoHandleClick, false);
    who_we_are.addEventListener("click", whoWeAreHandleClick, false);
    where_we_work.addEventListener("click", whereWeWorkHandleClick, false);
  })();
});

/*
//@ sourceMappingURL=main.map
*/
