// Generated by CoffeeScript 1.6.2
define(['order!login', 'order!donation', 'order!svg-pie-chart'], function() {
  console.log("app is loaded");
  return (function() {
    var lazyLoadingEventHandlerFactory, wayToGiveHandleClick, wayToGiveModule, way_to_give, whatWeDoHandleClick, whatWeDoModule, what_we_do, whereWeWorkHandleClick, whereWeWorkModule, where_we_work, whoWeAreHandleClick, whoWeAreModule, who_we_are;

    way_to_give = document.getElementById("way-to-give");
    what_we_do = document.getElementById("what-we-do");
    who_we_are = document.getElementById("who-we-are");
    where_we_work = document.getElementById("where-we-work");
    wayToGiveModule = null;
    whatWeDoModule = null;
    whoWeAreModule = null;
    whereWeWorkModule = null;
    lazyLoadingEventHandlerFactory = function(module, modulePath) {
      var clickEventHandler;

      clickEventHandler = function(event) {
        if (module === "loading") {
          return;
        }
        if (module !== null) {
          return module.render();
        } else {
          module = "loading";
          return require([modulePath], function(ModuleObject) {
            module = new ModuleObject();
            return module.render();
          });
        }
      };
      return clickEventHandler;
    };
    wayToGiveHandleClick = lazyLoadingEventHandlerFactory(wayToGiveModule, "modules/way-to-give");
    whatWeDoHandleClick = lazyLoadingEventHandlerFactory(whatWeDoModule, "modules/what-we-do");
    whoWeAreHandleClick = lazyLoadingEventHandlerFactory(whoWeAreModule, "modules/who-we-are");
    whereWeWorkHandleClick = lazyLoadingEventHandlerFactory(whereWeWorkModule, "modules/where-we-work");
    way_to_give.addEventListener("click", wayToGiveHandleClick, false);
    what_we_do.addEventListener("click", whatWeDoHandleClick, false);
    who_we_are.addEventListener("click", whoWeAreHandleClick, false);
    where_we_work.addEventListener("click", whereWeWorkHandleClick, false);
  })();
});

/*
//@ sourceMappingURL=main.map
*/
