// Generated by CoffeeScript 1.6.2
define(["newContentLoader"], function(contentLoader) {
  var genericModule;

  genericModule = function(moduleId) {
    return {
      render: function(button, containerId, dataUrl) {
        return contentLoader.getNewContent(button, containerId, dataUrl);
      }
    };
  };
  return genericModule;
});

/*
//@ sourceMappingURL=generic-module.map
*/
