// Generated by CoffeeScript 1.6.2
define(["newContentLoader"], function(contentLoader) {
  var wayToGive;

  console.log("way-to-give module is loaded");
  wayToGive = function() {
    return {
      rendered: false,
      render: function() {
        var dataUrl, newContainerID, whatWeDoButton;

        whatWeDoButton = "way-to-give";
        newContainerID = "way-to-give-container";
        dataUrl = "assets/html-includes/way-to-give.html";
        contentLoader.getNewContent(whatWeDoButton, newContainerID, dataUrl);
        return console.log("way-to-give module is rendered");
      },
      init: function() {
        return console.log("way-to-give init");
      }
    };
  };
  return wayToGive;
});

/*
//@ sourceMappingURL=way-to-give.map
*/
