// Generated by CoffeeScript 1.6.2
define(["newContentLoader"], function(NewSection) {
  var wayToGive;

  console.log("what-we-do module is loaded");
  wayToGive = function() {
    return {
      render: function() {
        var dataUrl, module_button, newContainerID;

        module_button = "what-we-do";
        newContainerID = "what-we-do-container";
        dataUrl = "assets/html-includes/what-we-do.html";
        NewSection.getNewContent(module_button, newContainerID, dataUrl);
        return console.log("what-we-do module is rendered");
      }
    };
  };
  return wayToGive;
});

/*
//@ sourceMappingURL=what-we-do.map
*/
