// Generated by CoffeeScript 1.6.2
define(["newContentLoader"], function(NewSection) {
  var whereWeWork;

  console.log("where-we-work module is loaded");
  whereWeWork = function() {
    return {
      render: function() {
        var dataUrl, module_button, newContainerID;

        module_button = "where-we-work";
        newContainerID = "where-we-work-container";
        dataUrl = "assets/html-includes/where-we-work.html";
        NewSection.getNewContent(module_button, newContainerID, dataUrl);
        return console.log("where-we-work module is rendered");
      }
    };
  };
  return whereWeWork;
});

/*
//@ sourceMappingURL=where-we-work.map
*/
